# Generated by Django 5.1.6 on 2025-02-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='image-coming-soon-placeholder-01-660x660.png', max_length=500),
        ),
    ]
